export const ActionTypes = {
    GET_CLASSES_LIST: 'GET_CLASSES_LIST',
    GET_CLASSES_LIST_SUCCESS : 'GET_CLASSES_LIST_SUCCESS',
    GET_CLASSES_LIST_ERROR : 'GET_CLASSES_LIST_ERROR',
    // all projects
    GET_PROJECTS_LIST_SUCCESS : 'GET_PROJECTS_LIST_SUCCESS',
    GET_PROJECTS_LIST_ERROR : 'GET_PROJECTS_LIST_ERROR',
    // all actions
    GET_PROJECT_ACTIONS_SUCCESS : 'GET_PROJECT_ACTIONS_SUCCESS',
    GET_PROJECT_ACTIONS_ERROR: 'GET_PROJECT_ACTIONS_ERROR',
    // classe
    SELECT_CLASSE : 'SELECT_CLASSE',
    // stats
    GET_STATS : 'GET_STATS',
    GET_STATS_SUCCESS : 'GET_STATS_SUCCESS',
    GET_STATS_ERROR : 'GET_STATS_ERROR',
    // projects
    SELECT_PROJECTS : 'SELECT_PROJECTS',
    // SELECT_DEFAULT_PROJECTS : 'SELECT_DEFAULT_PROJECTS',
    SHOW_PROJECT : 'SHOW_PROJECT',
    HIDE_PROJECT : 'HIDE_PROJECT',
    // time
    SET_TIME_VALUE : 'SET_TIME_VALUE'
}
