export const ActionTypes = {
    GET_STUDENTS_LIST: 'GET_STUDENTS_LIST',
    GET_STUDENTS_LIST_SUCCESS : 'GET_STUDENTS_LIST_SUCCESS',
    GET_STUDENTS_LIST_ERROR : 'GET_STUDENTS_LIST_ERROR',
    GET_PROJECTS_LIST_SUCCESS : 'GET_PROJECTS_LIST_SUCCESS',
    GET_PROJECTS_LIST_ERROR : 'GET_PROJECTS_LIST_ERROR',
    GET_PROJECT_ACTIONS_SUCCESS : 'GET_PROJECT_ACTIONS_SUCCESS',
    GET_PROJECT_ACTIONS_ERROR: 'GET_PROJECT_ACTIONS_ERROR',
    SET_TIME_VALUE : 'SET_TIME_VALUE',
    SELECT_CLASSE : 'SELECT_CLASSE'
}
