export const ActionTypes = {
    GET_STUDENTS_LIST: 'GET_STUDENTS_LIST',
    GET_STUDENTS_LIST_SUCCESS : 'GET_STUDENTS_LIST_SUCCESS',
    GET_STUDENTS_LIST_ERROR : 'GET_STUDENTS_LIST_ERROR',
    GET_PROJECTS_LIST_SUCCESS : 'GET_PROJECTS_LIST_SUCCESS',
    GET_PROJECTS_LIST_ERROR : 'GET_PROJECTS_LIST_ERROR'
}
